version: '3.9'
services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    environment:
      POSTGRES_DB: skinscan
      POSTGRES_USER: skinscan
      POSTGRES_PASSWORD: skinscan
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "skinscan"]
      interval: 5s
      timeout: 3s
      retries: 10
  
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql+asyncpg://skinscan:skinscan@db:5432/skinscan
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
      STORE_IMAGES: "false"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: