services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skinscan
      POSTGRES_USER: skinscan
      POSTGRES_PASSWORD: skinscan
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://skinscan:skinscan@db:5432/skinscan
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
      STORE_IMAGES: "false"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: